baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "LayneZhao Blog"

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"

[params]
  # DoIt theme version
  version = "0.3.X"
  # DoIt CHANGED | 0.2.11 site default theme ("light", "dark", "black", "auto")
  defaultTheme = "light"
  # DoIt NEW | 0.2.0 date format
  dateFormat = "2006-01-02"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]
  # [试验性功能] 缓存markdown中的图片链接到本地，详情请见：https://github.com/HEIGE-PCloud/DoIt/pull/860#issue-1574342372
  cacheRemoteImages = true
  # [Experimental] generate image srcset attribute with hugo image processing feature.
  optimizeImages = true
  # [Experimental] resize method for srcset attribute in optimizeImages, more info: https://gohugo.io/content-management/image-processing/#image-processing-options
  srcsetSmallResizeMethod = "700x webp Lanczos q75"
  srcsetDefaultResizeMethod = "1200x webp Lanczos q75"
  srcsetLargeResizeMethod = "2000x webp Lanczos q75"

  # DoIt NEW | 0.2.0 Search config
  [params.search]
    enable = true
    # type of search engine ("algolia", "fuse")
    type = "fuse"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # DoIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # DoIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # DoIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # DoIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false

  [params.image]
    # cache remote images for better optimisations
    cacheRemote = true
    # Image resizing and optimisation
    optimise = true

  # Header config
  [params.header]
    # DoIt NEW | 0.2.11 Theme change mode
    # theme change mode ("switch", "select")
    themeChangeMode = "select"
    # DoIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "LayneZhao Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # DoIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    # DoIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # DoIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # DoIt NEW | 0.2.14 Hosted on (HTML format is supported)
    # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
    hostedOn = ''
    # DoIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # DoIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2019
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


  # DoIt NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 10
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
    # DoIt NEW | 0.2.13 recently updated posts settings
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10

  # DoIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 10
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    # DoIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # DoIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # DoIt CHANGED | 0.2.0 Page config
  [params.page]
    # DoIt NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false
    # whether to enable last modified time
    enableLastMod = true
    # whether to enable word count
    enableWordCount = true
    # whether to enable reading time estimation
    enableReadingTime = true
    # DoIt NEW | 0.2.13 outdated article reminder config
    [params.page.outdatedArticleReminder]
      enable = false
      # Display the reminder if the last modified time is more than 90 days ago.
      reminder = 90
      # Display warning if the last modified time is more than 180 days ago.
      warning = 180
    # DoIt NEW | 0.2.0 Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # DoIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
      keepStatic = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # DoIt CHANGED | 0.2.0 KaTeX mathematical formulas
    [params.page.math]
      enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
      # Use MathJax instead of KaTeX
      mathjax = false
    # DoIt NEW | 0.2.0 Code config
    [params.page.code]
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    # DoIt NEW | 0.2.14 Table config
    [params.page.table]
      # whether to enable sorting in the tables
      sort = true
    # DoIt CHANGED | 0.2.0 Comment config
    [params.page.comment]
      enable = true
      # DoIt NEW | 0.2.13 giscus comment config
      [params.page.comment.giscus]
        enable = false
        # owner/repo
        dataRepo = "zhyine/zhyine.github.io"
        dataRepoId = "R_kgDOMNWCNw"
        dataCategory = "Announcements"
        dataCategoryId = "DIC_kwDOMNWCN84CgcNo"
        dataMapping = "pathname"
        dataReactionsEnabled = "1"
        dataEmitMetadata = "0"
        dataInputPosition = "bottom"
        lightTheme = "light"
        darkTheme = "dark"
        dataLang = "en"
        dataLoading = "lazy"

  # DoIt NEW | 0.2.0 Analytics config
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # whether to anonymize IP
      anonymizeIP = true
    # DoIt NEW | 0.2.13 Baidu Analytics
    [params.analytics.baidu]
      id = ""
    # DoIt NEW | 0.2.14 Cloudflare Analytics
    [params.analytics.cloudflare]
      token = ""
  
  # DoIt CHANGED | 0.2.7 CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # located in "themes/DoIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
